//ONE TYPE FOR ADDING A CHARACTER AND ONE FOR DELETING

export const ADD_CHARACTER = "ADD_CHARACTER"

export const REMOVE_CHARACTER = "REMOVE_CHARACTER"

export const SEARCH_CHARACTER_SUCCESS = "SEARCH_CHARACTER_SUCCESS"

export const SEARCH_CHARACTER_FAIL = "SEARCH_CHARACTER_FAIL"

export const SHOW_CHARACTER = "SHOW_CHARACTER"



